import type { AppLocale } from "./types/index.ts";

/** Juz 1–30 localized names (Madinah 604 edition). */
export const JUZ_NAMES: Record<AppLocale, Record<number, string>> = {
  en: {
    1: "Alif Lam Meem",
    2: "Sayaqool",
    3: "Tilka ar-Rusul",
    4: "Lan tanaloo",
    5: "Wal muhsanatu",
    6: "La yuhibbullah",
    7: "Wa idha sami'oo",
    8: "Wa law annana",
    9: "Qalal malao",
    10: "Wa'lamu",
    11: "Yatazeroon",
    12: "Wa maa min dabbatin",
    13: "Wa maa ubarri'u",
    14: "Rubama",
    15: "Subhanalladhi",
    16: "Qal alam",
    17: "Iqtaraba",
    18: "Qad aflaha",
    19: "Wa qalalladhina",
    20: "A'man khalaq",
    21: "Utlu ma oohiya",
    22: "Wa man yaqnut",
    23: "Wa maa li",
    24: "Faman azlam",
    25: "Elayhi yuradd",
    26: "Ha'a Meem",
    27: "Qala fama khatbukum",
    28: "Qad sam'i Allahu",
    29: "Tabarakalladhi",
    30: "Amma",
  },
  ar: {
    1: "آلم",
    2: "سَيَقُولُ",
    3: "تِلْكَ الرُّسُلُ",
    4: "لَنْ تَنَالُوا",
    5: "وَالْمُحْصَنَاتُ",
    6: "لَا يُحِبُّ اللَّهُ",
    7: "وَإِذَا سَمِعُوا",
    8: "وَلَوْ أَنَّنَا",
    9: "قَالَ الْمَلَأُ",
    10: "وَاعْلَمُوا",
    11: "يَعْتَزِرُونَ",
    12: "وَمَا مِنْ دَابَّةٍ",
    13: "وَمَا أُبَرِّئُ",
    14: "رُبَمَا",
    15: "سُبْحَانَ الَّذِي",
    16: "قَالَ أَلَمْ",
    17: "اقْتَرَبَ",
    18: "قَدْ أَفْلَحَ",
    19: "وَقَالَ الَّذِينَ",
    20: "أَمَّنْ خَلَقَ",
    21: "اتْلُ مَا أُوحِيَ",
    22: "وَمَنْ يَقْنُتْ",
    23: "وَمَا لِي",
    24: "فَمَنْ أَظْلَمُ",
    25: "إِلَيْهِ يُرَدُّ",
    26: "حم",
    27: "قَالَ فَمَا خَطْبُكُمْ",
    28: "قَدْ سَمِعَ اللَّهُ",
    29: "تَبَارَكَ الَّذِي",
    30: "عَمَّ",
  },
  de: {
    1: "Alif Lam Mim",
    2: "Sie werden sagen",
    3: "Diese Gesandten",
    4: "Ihr werdet nicht erlangen",
    5: "Und die keusch gehaltenen Frauen",
    6: "Allah liebt nicht",
    7: "Und wenn sie hören",
    8: "Und wenn Wir wahrlich",
    9: "Die Vornehmen sagten",
    10: "Und wisset",
    11: "Sie entschuldigen sich",
    12: "Und es gibt kein Lebewesen",
    13: "Und ich stelle niemanden frei",
    14: "Vielleicht",
    15: "Preis sei Dem",
    16: "Er sagte: Hattest du nicht",
    17: "Es naht sich",
    18: "Wahrlich erfolgreich sind",
    19: "Und diejenigen sagten",
    20: "Hat Der erschaffen",
    21: "Verkünde, was offenbart wurde",
    22: "Und wer demütig ist",
    23: "Und was ist mit mir",
    24: "Wer ist ungerechter",
    25: "Ihm wird zurückgebracht",
    26: "Ha Mim",
    27: "Er sagte: Was ist eure Angelegenheit",
    28: "Allah hat wahrlich gehört",
    29: "Gepriesen sei Der",
    30: "Amma",
  },
};

export function getJuzName(juz: number, locale: AppLocale): string {
  return JUZ_NAMES[locale]?.[juz] ?? JUZ_NAMES.en[juz] ?? `Juz ${juz}`;
}
